=head1 NAME

JSON::Functions::XS - Easy-to-use functional JSON-Perl convertions 

=head1 SYNOPSIS

  use JSON::Functions::XS qw(json_bytes2perl perl2json_bytes);
  
  print perl2json_bytes $obj;
  print json_bytes2perl $json;

=head1 DESCRIPTION

The C<JSON::Functions::XS> module provides various useful functions to
decode or encode JSON data.  These functions are wrappers; actual
conversion is enforced by the L<JSON::XS> module.

=head1 FUNCTIONS

No function is exposed by default - you have to specify one or more
functions to use after the module name:

  use JSON::Functions::XS qw(json_bytes2perl json_chars2perl);

=over 4

=item $perl_obj = json_bytes2perl $json_byte_string

Converts a JSON data represented as a byte string encoded in C<utf8>
into Perl data structure.

=item $perl_obj = json_chars2perl $json_char_string

Converts a JSON data represented as a character string into Perl data
structure.

=item $perl_obj = file2perl $path_class_file

Converts a JSON contained in a file encoded in C<utf8> specified by
the L<Path::Class::File> object into Perl data structure.

=item $json_byte_string = perl2json_bytes $perl_obj

Converts a Perl data into JSON represented as a byte string encoded in
C<utf8>.

=item $json_byte_string = perl2json_bytes_for_record $perl_obj

Converts a Perl data into JSON represented as a byte string encoded in
C<utf8>, pretty-printed.

=item $json_char_string = perl2json_chars $perl_obj

Converts a Perl data into JSON represented as a character string.

=item $json_char_string = perl2json_chars_for_record $perl_obj

Converts a Perl data into JSON represented as a character string,
pretty-printed.

=back

=head1 SEE ALSO

L<JSON::XS>.

L<Path::Class>.

RFC 4627 (JSON) <http://tools.ietf.org/html/rfc4627>.

ECMAScript5 The JSON Object <http://es5.github.com/#x15.12>.

=head1 DEVELOPMENT

Latest version of the module is available from the GitHub repository:

=over 4

=item GitHub

<https://github.com/wakaba/perl-json-functions-xs>.

=item Travis CI

<http://travis-ci.org/wakaba/perl-json-functions-xs>.

=item Tarball

<http://wakaba.github.com/packages/perl/#JSON-Functions-XS>.

=back

=head1 HISTORY

=over 4

=item 1.0 (2010-08-18)

First packaged version.

=item 1.1 (2011-09-15)

Improved UTF-7 safeness.

=back

=head1 AUTHOR

Wakaba (id:wakabatan) <wakabatan@hatena.ne.jp>

=head1 LICENSE

Copyright 2009-2011 Hatena <http://www.hatena.ne.jp/>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
